DARES = [
    "Do 20 push-ups right now and send proof!",
    "Send a funny selfie to the group.",
    "Speak in an accent for the next 3 messages.",
    "Do your best dance and describe it in detail.",
    "Send a voice message singing your favorite song.",
    "Change your group profile picture to something funny.",
    "Let the person above you write your status for 24 hours.",
    "Do 30 jumping jacks and send a video!",
    "Imitate another group member (describe in detail).",
    "Share your most embarrassing photo.",
    "Talk in rhymes for the next 5 messages.",
    "Do your best celebrity impression in text.",
    "Send a message to your crush (screenshot it!).",
    "Post a throwback photo from 5+ years ago.",
    "Let someone else choose your profile picture for a week.",
    "Write a funny poem about someone in the group.",
    "Share the last photo in your gallery.",
    "Do 50 jumping jacks.",
    "Share your screen time report.",
    "Send a meme that describes your life right now.",
    "Text your mom 'I love you' right now.",
    "Do 10 burpees and send proof.",
    "Share an embarrassing voice note.",
    "Let someone send a text from your phone.",
    "Post a story saying 'I lost a bet'.",
]
