TRUTHS = [
    "What's the most embarrassing thing you've ever done?",
    "What's your biggest fear?",
    "Have you ever told a lie to get out of trouble?",
    "What's the worst gift you've ever received?",
    "Who was your first crush?",
    "What's something you've never told anyone?",
    "What's your most embarrassing childhood memory?",
    "Have you ever cheated on a test?",
    "What's the biggest lie you've ever told?",
    "What's your guilty pleasure?",
    "Who in this group do you trust the most?",
    "What's the most childish thing you still do?",
    "Have you ever stalked someone on social media?",
    "What's your biggest insecurity?",
    "What's the worst date you've ever been on?",
    "If you could swap lives with someone for a day, who would it be?",
    "What's the most trouble you've been in?",
    "Have you ever ghosted someone?",
    "What's your most unpopular opinion?",
    "What's the craziest dream you've ever had?",
    "What's the most embarrassing thing in your search history?",
    "Who was your worst kiss?",
    "What's your biggest regret?",
    "Have you ever pretended to be sick to skip something?",
    "What's the longest you've gone without showering?",
]
